### ISSUE TITLE
Simplify the Deploy of the Web Site

### ISSUE THREAD

**Issue by myles** [gtalug/infrastructure#34]
- [x] Add a `deploy` user.
- [x] Get SSH Keys of people who will be deploying the web site and [add them like this](/gtalug/infrastructure/issues/4#issuecomment-50916788) so they can only `rsync`.
- [x] When someone pushes to the [Web Site Repo](/gtalug/website) it changes get published to the Web Site.
- [x] Get @cbbrowne to backup the `/home/deploy/.ssh/authorized_keys` file and any scripts made.

**Comment by avolkov** [comment]
I added @myles and mine ssh keys to the user deploy, changed permissions in /srv/www/*/html from user myles to user deploy, updated fabfile.py in [websites/fabfile.py](https://github.com/gtalug/website/commit/353ed1814a799b3ab27465acd7244222d30b5f61)

**Comment by myles** [comment]
Wrote the backup script <https://github.com/gtalug/backups/blob/master/scripts/backup-deploy-authorized_keys.sh>.
